---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: devops-services@marius.xyz
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - selector:
          dnsZones:
            - "lab.marius.xyz"
            - "labs.marius.xyz"
        dns01:
          route53:
            region: eu-west-1
            # hostedZoneID: ""
            accessKeyID: ""
            secretAccessKeySecretRef:
              name: devops-services-credentials
              key: aws_secret_access_key
