---
apiVersion: v1
kind: Service
metadata:
  namespace: elastic
  name: kibana-service
  labels:
    app: kibana
spec:
  type: NodePort
  selector:
    app: kibana
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
      name: webinterface
