apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: db
commonLabels:
  app: mongodb
resources:
  - common/namespace.yml
  # - mongodb/configmap.yml
  # - mongodb/secret.yml
  # - mongodb/pvc.yml
  # - mongodb/deploy.yml
  # - mongodb/service.yml
  - redis/secret.yml
  - redis/pvc.yml
  - redis/deploy.yml
  - redis/service.yml
